name: Build and Push Docker Images to Docker Hub and Trigger Google Cloud Run

on:
  push:
    branches:
      - misterfocusth/development-ci-cd
      - staging
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Create a JSON file from the secret
      - name: Create JSON file from secret
        run: |
          cd backend
          mkdir firebase
          echo '${{ secrets.FIREBASE_ADMIN_CREDENTIALS_JSON }}' > ./firebase/k-dorm-745f0-firebase-adminsdk-vpaem-b89972a630.json
          ls -l
        shell: bash

      # Step 6: Build and push the Docker images using docker-compose.dev.yml
      - name: Build and push Docker images
        run: |
          ls -l
          docker compose -f docker-compose.dev.yml build --no-cache
          docker push it65070219/k-dorm-backend:latest

  deploy_to_google_cloud_run:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      # Step 6: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Step 7: Redeploy to existing Google Cloud Run service
      - name: Deploy to existing Cloud Run service
        run: |
          gcloud run deploy k-dorm-backend \
            --image it65070219/k-dorm-backend:latest \
            --platform managed \
            --region asia-southeast1 \
            --allow-unauthenticated
